import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { StoreProvider } from "@/store/StoreProvider";
import "bootstrap/dist/css/bootstrap.min.css";
import "./global.css";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={font.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
